version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: go-backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=3306
      - DB_USER=root
      - DB_PASS=
      - DB_NAME=kai_balai_yasa
    volumes:
      - ./backend:/app

  frontend:
    build:
      context: ./frontend
    container_name: react-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend

  db:
    image: mysql:8.0
    container_name: kai-db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ""
      MYSQL_DATABASE: kai_balai_yasa
    ports:
      - "3306:3306"
    volumes:
      - kai_data:/var/lib/mysql

volumes:
  kai_data:
